### ISSUE TITLE
First time contribution

### ISSUE THREAD

**Issue by sohan2410** [sohan2410/GitFest#1]
- Fork this repo and clone into your local system.
- Create a folder
`CONTRIBUTORS/${college_name}/${current_year_of_course}/${your_name}/info.md`
- Write a short note about yourself in info.md

**Comment by AdiTyaa-Raj** [comment]
Hey @sohan2410 , Can you please assign this to me?

**Comment by sohan2410** [comment]
Sure, you can go ahead

**Comment by DCoder-1** [comment]
Hey @sohan2410 , Can you please assign the issue to me ?

**Comment by sohan2410** [comment]
Sure, go ahead

**Comment by pranit9000** [comment]
Hey, can you please assign this work to me.

**Comment by sohan2410** [comment]
No need of claiming this issue, you can send PR directly.

**Comment by pranit9000** [comment]
I have sended a PR,please merg it
