### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by sohan2410** [sohan2410/GitFest#2]
- You can refer the  docs from [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- Please add best practice PR template

**Comment by kishan-aghera** [comment]
Hello. I would like to take this issue.

**Comment by sohan2410** [comment]
@kishan-aghera I appreciate your desire to contribute, but I must regret to inform you that this repository was created to support IIITM Gwalior students. I wish you luck in finding more fantastic repositories to contribute to!

**Comment by kishan-aghera** [comment]
Okay, no problem!

**Comment by iamhariom0228** [comment]
hey @sohan2410 sir, can I take this issue and work on it?

**Comment by sohan2410** [comment]
@iamhariom0228 sure, go ahead.
